// e2ba642e-bbc2-48c9-b5f5-c8f0978c871e
// 888       888        d8888 8888888b.  888b    888 8888888 888b    888  .d8888b. 
// 888   o   888       d88888 888   Y88b 8888b   888   888   8888b   888 d88P  Y88b
// 888  d8b  888      d88P888 888    888 88888b  888   888   88888b  888 888    888
// 888 d888b 888     d88P 888 888   d88P 888Y88b 888   888   888Y88b 888 888       
// 888d88888b888    d88P  888 8888888P"  888 Y88b888   888   888 Y88b888 888  88888
// 88888P Y88888   d88P   888 888 T88b   888  Y88888   888   888  Y88888 888    888
// 8888P   Y8888  d8888888888 888  T88b  888   Y8888   888   888   Y8888 Y88b  d88P
// 888P     Y888 d88P     888 888   T88b 888    Y888 8888888 888    Y888  "Y8888P88
// NOTE: This file was generated automatically
// DO NOT EDIT THIS FILE DIRECTLY
void 0;

import type {x509ExtensionNames} from "./types/x509ExtensionNames.mts"

export function getx509ExtensionNames(): x509ExtensionNames {
	return [
		"AuthorityKeyIdentifier",
		"!AuthorityKeyIdentifier",
		"BasicConstraints",
		"!BasicConstraints",
		"CRLDistributionPoints",
		"!CRLDistributionPoints",
		"ExtendedKeyUsage",
		"!ExtendedKeyUsage",
		"KeyUsage",
		"!KeyUsage",
		"NameConstraints",
		"!NameConstraints",
		"SubjectAltName",
		"!SubjectAltName",
		"SubjectKeyIdentifier",
		"!SubjectKeyIdentifier",
	]
}
